import { FoodItem } from '../types';

export const demoFoods: FoodItem[] = [
    {
        id: 'food-1',
        name: 'Chicken Breast',
        brand: 'Generic',
        calories_per_100g: 165,
        protein_per_100g: 31,
        carbs_per_100g: 0,
        fat_per_100g: 3.6,
        serving_size_g: 100,
    },
    {
        id: 'food-2',
        name: 'Brown Rice',
        brand: 'Generic',
        calories_per_100g: 112,
        protein_per_100g: 2.6,
        carbs_per_100g: 23.5,
        fat_per_100g: 0.9,
        serving_size_g: 150,
    },
    {
        id: 'food-3',
        name: 'Broccoli',
        brand: 'Generic',
        calories_per_100g: 34,
        protein_per_100g: 2.8,
        carbs_per_100g: 7,
        fat_per_100g: 0.4,
        serving_size_g: 100,
    },
    {
        id: 'food-4',
        name: 'Eggs',
        brand: 'Generic',
        calories_per_100g: 155,
        protein_per_100g: 13,
        carbs_per_100g: 1.1,
        fat_per_100g: 11,
        serving_size_g: 50,
    },
    {
        id: 'food-5',
        name: 'Greek Yogurt',
        brand: 'Fage',
        calories_per_100g: 97,
        protein_per_100g: 9,
        carbs_per_100g: 4,
        fat_per_100g: 5,
        serving_size_g: 170,
    },
    {
        id: 'food-6',
        name: 'Oatmeal',
        brand: 'Quaker',
        calories_per_100g: 389,
        protein_per_100g: 16.9,
        carbs_per_100g: 66.3,
        fat_per_100g: 6.9,
        serving_size_g: 40,
    },
    {
        id: 'food-7',
        name: 'Banana',
        brand: 'Generic',
        calories_per_100g: 89,
        protein_per_100g: 1.1,
        carbs_per_100g: 23,
        fat_per_100g: 0.3,
        serving_size_g: 120,
    },
    {
        id: 'food-8',
        name: 'Salmon',
        brand: 'Generic',
        calories_per_100g: 208,
        protein_per_100g: 20,
        carbs_per_100g: 0,
        fat_per_100g: 13,
        serving_size_g: 150,
    },
];
